# Generated by Django 5.1.2 on 2024-10-19 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=3000000, max_digits=10),
        ),
    ]
