# Generated by Django 5.1.2 on 2024-10-19 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_joblisting_due_date_joblisting_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
