# Generated by Django 5.1.2 on 2024-10-21 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def set_default_first_name(apps, schema_editor):
    User = apps.get_model('jobs', 'User')  # Replace 'your_app_name' with the actual app name
    for user in User.objects.all():
        if not user.first_name:
            user.first_name = user.username
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_joblisting_posted_by'),
    ]

    operations = [
        migrations.RunPython(set_default_first_name),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joblisting'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'job')},
        ),
    ]
