# Generated by Django 5.1.2 on 2024-10-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_application_job_alter_application_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='location',
            field=models.CharField(default='Hyderabad', max_length=255),
        ),
    ]
