# Generated by Django 5.1.2 on 2024-10-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_joblisting_due_date_alter_joblisting_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, default='Btech', max_length=10, null=True),
        ),
    ]
