# Generated by Django 5.1.2 on 2024-10-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='OT_date',
            field=models.DateField(blank=True, default='2024-12-12', null=True),
        ),
    ]
